name: Unused Deps

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  udeps:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Set up nightly toolchain
        uses: dtolnay/rust-toolchain@f7ccc83f9ed1e5b9c81d8a67d7ad1a747e22a561 # nightly
        with:
          toolchain: nightly

      - name: Install cargo-udeps
        uses: taiki-e/install-action@3d30e7d625f7c928dccd48823053b03bb2f6ed05 # v2
        with:
          tool: cargo-udeps

      - name: Run cargo-udeps (release, all targets)
        run: |
          cargo udeps --workspace --all-targets --all-features --release
